### ISSUE TITLE
VMware Tools Installation Failed

### ISSUE THREAD

**Issue by lriverawong** [trodemaster/packer-macOS-11#10]
Hello!
I noticed that during a complete install that `vmware-tools` fails due to `SIP`/`kext`.

The error is `System Extension Blocked`. I know that this is addressed at the following line in your [setupsshlogin.sh](https://github.com/trodemaster/packer-macOS-11/blob/main/scripts/setupsshlogin.sh#L40) script, but it doesn't seem to persist.

I just wanted to let you know, great project otherwise!

**Comment by trodemaster** [comment]
This is a known issue as noted in the hashicorp discussion thread. https://discuss.hashicorp.com/t/building-macos-11-x-vms-with-packer-and-fusion/18178/16?u=trodemaster Quite a lot of the macOS configuration needs to be managed with profiles or MDM these days.
