### ISSUE TITLE
11.3 not completing install from full .iso

### ISSUE THREAD

**Issue by trodemaster** [trodemaster/packer-macOS-11#11]
As of Beta 5 installs of 11.3 are failing to configure the needed user and ssh configs. This results in the build stalling out at the initial setup window. I'm investigating changes to the packages or another method for running shell scripts directly in the correct context to configure the system settings. 

Workaround if you need a 11.3 VM is to install with 11.2.2 .iso and upgrade to 11.3. See readme for info on update configuration..

**Comment by thatnerdjosh** [comment]
@trodemaster it seems to have completed install for me, the only thing failing is the VMWare tools setup afaict

**Comment by trodemaster** [comment]
This issue has been resolved!!


# this command works 11.1 through 11.2.3
# it will install the OS on 11.3 through 11.4 beta 1 but the packages wont install or throw any errors in install.log
/Volumes/macOS\ Base\ System/Install*.app/Contents/Resources/startosinstall --agreetolicense --installpackage packer.pkg --volume /Volumes/11vm

# this command works on 11.1 through 11.4 Beta 1 and might even be a little bit faster
/Volumes/Image\ Volume/Install*.app/Contents/Resources/startosinstall --agreetolicense --installpackage packer.pkg --volume /Volumes/11vm
