### ISSUE TITLE
Clarifications

### ISSUE THREAD

**Issue by branylagaffe** [trodemaster/packer-macOS-11#12]
Hello there !

I've been following this project since quite sometimes, and are actually working on/with it for my job.
I got a question about it.

- How have you created the `packer.dmg`  and the `ssh-install PKG`? (I tried to reproduce both and I still can't skip the Installation process)
- Why does the Feedback assistant keep poking up even if it's no beta ?

Anyway thanks for work!

**Comment by trodemaster** [comment]
https://github.com/trodemaster/packer-macOS-11#username--password

The packer.pkg is generated using the following.
https://github.com/gregneagle/pycreateuserpkg

The other is created using http://s.sudre.free.fr/Software/Packages/about.html with the config file here. https://github.com/trodemaster/packer-macOS-11/blob/main/packages/setupsshlogin/setupsshlogin.pkgproj

I only see feedback assistant when beta OS is installed. check this one out and make sure it's set to none. That will not install pre-release updates.
https://github.com/trodemaster/packer-macOS-11#install-pre-release-software-updates

Are you trying to modify the username and passoword of the account used by packer? If so an easy solution is to simply add a second user account via an additional script.

**Comment by damonbreeden** [comment]
smth to note, i had to build the `packer.pkg` file on macOS 11 to get it to work properly with the install
my 'hypervisor' is macOS 10.15 and I had been building it there and it just failed to make any changes (kept creating a user `packer`), but after running `makepkgs.sh` on my laptop & pushing the resulting `packer.pkg` it seems to be working ok
