### ISSUE TITLE
what is the purpose of bootstrap.pkg

### ISSUE THREAD

**Issue by damonbreeden** [trodemaster/packer-macOS-11#13]
hi, genuinely asking what the purpose of `bootstrap.pkg` is
it gets built from the directory `packages/bootstrap` which is full of empty files
i don't see `bootstrap.pkg` (only `bootstrap.sh`) referred to anywhere in the `hcl` or anywhere else
seems that the users are created via `packer.pkg`, and ssh is enabled via `setupsshlogin.pkg`, and i can't see a need for anything else to bootstrap the image

thanks for your work

**Comment by trodemaster** [comment]
Those are files for some work in progress that has stalled out. The intention was to combine user creation and bootstrap.pkg functions into a single package that would allow for easier username/password customization. Ideally, the pkg build process would be simplified as well. 

I may return to that effort after Monterey version of the template is completed.

**Comment by damonbreeden** [comment]
thx for the clarification
