### ISSUE TITLE
more steps are needed to change the username/password applied at login

### ISSUE THREAD

**Issue by damonbreeden** [trodemaster/packer-macOS-11#14]
it would be appreciated if you could share your workflow to generate the `setupsshlogin.pkg` file

specifically this line 
`echo 'packer     ALL=(ALL)       NOPASSWD: ALL' >/private/etc/sudoers.d/packer`

doesn't get updated with a new username when that changes (in `packages/setupsshlogin/build/setupsshlogin.pkg`)

a different way to make sure that sudoers get sudo access is to add this line

`%sudo ALL=NOPASSWD: ALL`
to `/etc/sudoers` or smth inside of `sudoers.d`

**Comment by damonbreeden** [comment]
these are the changes that i made: 

```
user@macmini3:~/packer-macOS-11$ cat scripts/makepkgs.sh 
#!/bin/bash

# pkgbuild --identifier com.damon.setup --nopayload --scripts damon/ ../packages/damon/build/damon.pkg
# always create an empty dir even for script-only package
rootdir=$(mktemp)
pkgbuild --ownership recommended --identifier com.damon.setup --root $rootdir --scripts damon/ --version $(date '+%Y%m%d') ../packages/damon/build/damon.pkg
productbuild --package ../packages/damon/build/damon.pkg --identifier com.damon.setup --version $(date '+%Y%m%d') ../http/damon.pkg
rm -rf $rootdir
../submodules/pycreateuserpkg/createuserpkg -n user -u 502 -f user -a -A -d -V 3 -i com.netjibbing.packer -p damon ../http/packer.pkg

user@macmini3:~/packer-macOS-11$ rg user_ -A2 macOS_11.pkr.hcl 
15:variable "user_password" {
16-  type    = string
17-  default = "damon"
--
20:variable "user_username" {
21-  type    = string
22-  default = "user"

user@macmini3:~/packer-macOS-11$ rg damon http/bootstrap.sh 
17:  /Volumes/Image\ Volume/Install*.app/Contents/Resources/startosinstall --agreetolicense --rebootdelay 90 --installpackage packer.pkg --installpackage damon.pkg --volume /Volumes/11vm && break

user@macmini3:~/packer-macOS-11$ ls -lh http/
total 36K
-rw-r--r-- 1 user staff 2.9K Oct 15 16:50 damon.pkg
-rw-r--r-- 1 user staff 2.5K Oct 14 19:28 bootstrap.pkg
-rw-r--r-- 1 user staff 1008 Oct 14 22:34 bootstrap.sh
-rw-r--r-- 1 user staff  17K Oct 15 16:50 packer.pkg
-rw-r--r-- 1 user staff 3.0K Oct 14 19:43 setupsshlogin.pkg

user@macmini3:~/packer-macOS-11$ tree packages/damon/
packages/damon/
└── build
    └── damon.pkg

1 directory, 1 file

user@macmini3:~/packer-macOS-11$ tree scripts/damon/
scripts/damon/
└── postinstall

0 directories, 1 file

user@macmini3:~/packer-macOS-11$ rg user scripts/damon/postinstall 
13:# sudo nopasswd for user
14:echo 'user     ALL=(ALL)       NOPASSWD: ALL' >/private/etc/sudoers.d/user

user@macmini3:~/packer-macOS-11$ ls -lh scripts/damon/postinstall
-rwxr-xr-x 1 user staff 2.7K Oct 14 15:57 scripts/damon/postinstall

user@macmini3:~/packer-macOS-11$ ls -lh /tmp/damon/damon.pkg/Scripts/postinstall 
-rwxr-xr-x 1 user user 2.7K Oct 14 15:57 /tmp/damon/damon.pkg/Scripts/postinstall
```

**Comment by trodemaster** [comment]
Have you considered adding a second user account later in the build
process? That’s what I’m doing outside this packer process. I then trash
the packer user.

**Comment by damonbreeden** [comment]
for the moment i will fix it by using the original `setupsshlogin.pkg` but with my new user account put in place by the `packer.pkg` and i added this line into `ossettings.sh`:

`HISTIGNORE='*sudo -S*'; echo <password> | sudo -S -k -p '' sed -i '' -e 's/^root.*/root            ALL = (ALL) NOPASSWD:ALL/' -e 's/^%admin.*/%admin          ALL = (ALL) NOPASSWD:ALL/' /etc/sudoers`

this is the only actually missing part & i can remove the errant file at `/private/etc/sudoers.d/packer` later

**Comment by trodemaster** [comment]
Changes to the /etc/sudoers file are overwritten during major OS version upgrades. This template supports OS upgrades so any changes to sudoers are persisted in the sudoers.d/ files. 

I have simplified the process for changing username/passwords used in the packer build. See details here https://github.com/trodemaster/packer-macOS-11/blob/main/README.md#username--password
