### ISSUE TITLE
Willing to help to create a qemu version.

### ISSUE THREAD

**Issue by egandro** [trodemaster/packer-macOS-11#19]
This version runs with macOS-12.

https://github.com/kholia/OSX-KVM

However the installation is much nicer here.

Someone willing to help?

**Comment by trodemaster** [comment]
It is possible to use qemu with hvf accelerator on a macOS x86 host to build a macOS x86 guest VM with opencore firmware that packer can work with. Getting all those components to work correctly together in a way that is fully automated will be quite a bit of work. I'm open to PRs that are complete and reasonable to support but I don't have any driving need for a qemu hypervisor solution for macOS vms on macOS.
