### ISSUE TITLE
How is packer.pkg made?

### ISSUE THREAD

**Issue by RLovelett** [trodemaster/packer-macOS-11#20]
Could you provide steps for someone to recreate `packer.pkg` and `setupsshlogin.pkg` from scratch? I would like to be able to recreate as much of this as possible from scratch.

**Comment by trodemaster** [comment]
If you're wanting to use this packer template and change the username and password combo see this part of the readme. https://github.com/trodemaster/packer-macOS-11#customize-username-password-hostname--ssh-key

The packer.pkg is created using this tool https://github.com/gregneagle/pycreateuserpkg . Changing the username and password in this package will cause breakage with the packer to build as the user/pass combo is needed in other parts of the build process.

The setupsshlogin.pkg is an installer package with a post install script. Payload for that is https://github.com/trodemaster/packer-macOS-11/blob/main/scripts/setupsshlogin.sh

Building and debugging these packages is quite painful. I used this tool to create the setupsshlogin pkg. http://s.sudre.free.fr/Software/Packages/about.html
