### ISSUE TITLE
Docs - mention that you need GNU coreutils

### ISSUE THREAD

**Issue by jclyons** [trodemaster/packer-macOS-11#21]
was getting command not found when running the installer bits scripts - had to install GNU coreutils from brew to get GNU 'realpath' (line 7) for the script to work

**Comment by trodemaster** [comment]
Thanks for the report! Looks like I can just remove that dependency from the script.

**Comment by trodemaster** [comment]
Closed with  ab7f466c166116642ada74187007a182d45f696d
