### ISSUE TITLE
Force Network adapter type

### ISSUE THREAD

**Issue by mcnahum** [trodemaster/packer-macOS-11#3]
Hi,
thanks for this tool... one option I didn't found:
Is there a way to force the Force Network adapter Type.
I would like to be in "Ethernet" instead of the "Share with my Mac" default mode...

**Comment by trodemaster** [comment]
It's best to change that setting after the VM is built. Otherwise packer will not know how to get the IP of the VM when building it. If you use https://www.packer.io/docs/builders/vmware/iso#vmx_data_post you can customize 99% of the settings you want after the build has completed.
