### ISSUE TITLE
macOS_1101_installer.shasum file

### ISSUE THREAD

**Issue by mcnahum** [trodemaster/packer-macOS-11#4]
Sorry if it's a stupid question but how the macOS_1101_installer.shasum file is supposed to be created?

**Comment by trodemaster** [comment]
The buildprerequs.sh script downloads macOS and creates the .iso file and checksum. If you just need to make only the checksum file check out https://github.com/trodemaster/packer-macOS-11/blob/bee7e00b55e5d8abaa0449e1e2af8a2079c11743/scripts/buildprerequs.sh#L40
