### ISSUE TITLE
Booting in Boot Manager

### ISSUE THREAD

**Issue by mcnahum** [trodemaster/packer-macOS-11#5]
I tried multiple way but when my VM start it's always on the boot manager...
it seams the ISO file cannot been use to boot... does I forgetting a step somewhere?

**Comment by trodemaster** [comment]
Sounds like your .iso is not good. Please ask usage questions in this new thread I created. https://discuss.hashicorp.com/t/building-macos-11-x-vms-with-packer-and-fusion/
