### ISSUE TITLE
Support virtualbox

### ISSUE THREAD

**Issue by fifar** [trodemaster/packer-macOS-11#7]
I'm using Vagrant + VirtualBox, while this repo uses VMware fusion. Is it easy to switch from fusion to virtualbox with most the code in this repo? Thanks a lot.

**Comment by trodemaster** [comment]
Please post questions in the linked discussion thread. https://discuss.hashicorp.com/t/building-macos-11-x-vms-with-packer-and-fusion/

**Comment by trodemaster** [comment]
Just to clarify I won't be supporting Virtualbox.
